on:
  push:
    branches:
      - master
name: Deploy Website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Get Latest Code
        uses: actions/checkout@v2.3.2

      - name: Sync Files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: kssas.com
          username: kssw4119
          password: iMsTQg38mKjd57
          server-dir: /public_html/ 
          script: |
            git checkout master
            git pull origin master
            git push all master
            

      - name: Install Dependencies
        working-directory: ./laravel/
        
        run: composer install --no-dev --optimize-autoloader
         
     
