on:
  push:
    branches:
      - master
name: Deploy Website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:7.4
        env:
          MYSQL_USER: kssw4119_kssas_original_user
          MYSQL_PASSWORD: DH@i5H2dMrvphW6
          MYSQL_DATABASE: kssw4119_kssas_original_db
          MYSQL_ROOT_PASSWORD: DH@i5H2dMrvphW6
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Get Latest Code
        uses: actions/checkout@v2.3.2

      - name: Sync Files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: kssas.com
          username: kssw4119
          password: iMsTQg38mKjd57
          server-dir: /public_html/ 

      - name: Install Dependencies
        working-directory: ./laravel/
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Run Migration
        working-directory: ./laravel/
        run: |
          php artisan migrate --force
