on:
  push:
    branches:
      - master
name: Deploy Website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Code
        uses: actions/checkout@v2.3.2

      - name: Sync Files
        uses: appleboy/ssh-action@master
        with:
          host: kssas.com
          username: kssw4119
          password: iMsTQg38mKjd57
          script: '/public_html/ && ./server_deploy.sh'

      - name: Install Dependencies
        working-directory: ./laravel/
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Run Migration
        working-directory: ./laravel/
        run: |
          php artisan migrate --force
